version: '3'

services:
  server:
    container_name: iot-backend
    env_file:
      - .env
    environment:
      - PORT=3000
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT:-3000}:3000